# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.


title:
  en: Bright Sky Games
  zh-Hans: Bright Sky Games
  zh-Hant: Bright Sky Games
  ja: Bright Sky Games
lang_natural:
  en: en
  zh-Hans: 简体
  zh-Hant: 繁體
  ja: 日本語
lang_ext:
  en:
  zh-Hans: -zhs
  zh-Hant: -zht
  ja: -ja
email: brightskygames@me.com
description: 
  en: > # this means to ignore newlines
    Logic puzzle games including Sudoku, Kakuro. Many variations to popular logic puzzles. 
    Available in iOS and Android devices. Play Now!
  zh-Hans: >
    适用于iPhone,iPad和安卓系统的数独游戏. 数独是一种逻辑性的数字填充游戏. 还有其他游戏包括: 武士数独, 数和. 立即下载.
  zh-Hant: >
    免費的 iOS, Android 數字填充遊戲. 數獨是一種邏輯性的數字填充遊戲. 還有其他遊戲包括: 武士數獨, 數和. 立即下載.
  ja: >
    無料で遊べる脳トレパズルゲームアプリ。 サムライ数独、カクロなどのロジックパズルゲーム。 多くのバリエーション。
    iOSとAndroid端末で利用可能。今すぐダウンロード。
keywords:
  en: free logic puzzles, samurai, sudoku, puzzle games, mobile games, ipad games, kakuro, logic games, variants, variations, hyper sudoku, sudoku revolution
  zh-Hans: 数独,数和,数独游戏,数独技巧,数独网站,数独软件,sudoku,在线数独,免费
  zh-Hant: 數獨,數和,解謎遊戲,邏輯遊戲,數獨遊戲,推論,方框,邏輯,謎題,橫行,答案,解答,方形,正方形,空格,方格,數字,演譯
  ja: 無料ロジックパズル, 数独, すうどく, パズルゲーム, ナンプレ, ロジックゲーム, バラエティ, バリエーション, パクロス, 問題集
index:
  en:
  zh-Hans: index-zhs.html
  zh-Hant: index-zht.html
  ja: index-ja.html
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com
twitter_username: brightskygames
github_username:  brightskygames
facebook_username: brightskygames

# Build settings
markdown: kramdown
theme: minima
plugins:
  - jekyll-feed

# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
# exclude:
#   - Gemfile
#   - Gemfile.lock
#   - node_modules
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
